//! Unit tests against the shared cross-language test vector (generated by the TS SDK).

use hour_consent::consent::{contributor_key_id, ConsentFields};
use hour_consent::error::ConsentError;
use hour_consent::instruction::ConsentInstruction;
use hour_consent::precompile::{
    build_single_signature_data, extract_single_signature, SAME_INSTRUCTION,
};
use hour_consent::processor::check_consent;
use hour_consent::state::{ConsentRecord, CONSENT_RECORD_LEN};

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}
fn a<const N: usize>(s: &str) -> [u8; N] {
    hex(s).try_into().unwrap()
}

struct V {
    fields: ConsentFields,
    pubkey: [u8; 33],
    digest: [u8; 32],
    sig: [u8; 64],
    record_ix: Vec<u8>,
    precompile_ix: Vec<u8>,
}

fn vector() -> V {
    let j: serde_json::Value =
        serde_json::from_str(include_str!("../../../spec/test-vectors/consent-v1.json")).unwrap();
    let s = |k: &str| j[k].as_str().unwrap().to_string();
    V {
        fields: ConsentFields {
            release_id: a(&s("release_id")),
            split_version_hash: a(&s("split_version_hash")),
            contributor_id: a(&s("contributor_id")),
            nonce: s("nonce").parse().unwrap(),
            expiry: s("expiry").parse().unwrap(),
        },
        pubkey: a(&s("passkey_pubkey_compressed")),
        digest: a(&s("consent_digest")),
        sig: a(&s("signature_compact_low_s")),
        record_ix: hex(&s("record_consent_ix_data")),
        precompile_ix: hex(&s("secp256r1_ix_data")),
    }
}

#[test]
fn digest_matches_ts_sdk() {
    let v = vector();
    assert_eq!(v.fields.digest(), v.digest);
}

#[test]
fn contributor_key_id_matches_ts_sdk() {
    let v = vector();
    assert_eq!(contributor_key_id(&v.pubkey), v.fields.contributor_id);
}

#[test]
fn instruction_pack_unpack_matches_ts_sdk() {
    let v = vector();
    assert_eq!(
        ConsentInstruction::RecordConsent(v.fields).pack(),
        v.record_ix
    );
    assert_eq!(
        ConsentInstruction::unpack(&v.record_ix).unwrap(),
        ConsentInstruction::RecordConsent(v.fields)
    );
}

#[test]
fn instruction_unpack_rejects_bad_data() {
    let v = vector();
    assert_eq!(
        ConsentInstruction::unpack(&[]),
        Err(ConsentError::InvalidInstructionData)
    );
    assert_eq!(
        ConsentInstruction::unpack(&v.record_ix[..112]),
        Err(ConsentError::InvalidInstructionData)
    );
    let mut bad = v.record_ix.clone();
    bad[0] = 7;
    assert_eq!(
        ConsentInstruction::unpack(&bad),
        Err(ConsentError::InvalidInstructionData)
    );
}

#[test]
fn precompile_data_matches_ts_sdk_and_parses() {
    let v = vector();
    let built = build_single_signature_data(&v.pubkey, &v.sig, &v.digest);
    assert_eq!(built, v.precompile_ix);
    let got = extract_single_signature(&built).unwrap();
    assert_eq!(got.public_key, v.pubkey);
    assert_eq!(got.message, &v.digest[..]);
}

#[test]
fn precompile_rejects_multiple_signatures_and_truncation() {
    let v = vector();
    let mut d = v.precompile_ix.clone();
    d[0] = 2;
    assert_eq!(
        extract_single_signature(&d),
        Err(ConsentError::UnsupportedSignatureCount)
    );
    assert_eq!(
        extract_single_signature(&[1]),
        Err(ConsentError::MalformedPrecompileData)
    );
    let short = &v.precompile_ix[..v.precompile_ix.len() - 1];
    assert_eq!(
        extract_single_signature(short),
        Err(ConsentError::MalformedPrecompileData)
    );
}

#[test]
fn precompile_rejects_cross_instruction_references() {
    let v = vector();
    // offsets struct starts at byte 2; each index field is at +2, +6, +12 within it.
    for idx_pos in [2 + 2, 2 + 6, 2 + 12] {
        let mut d = v.precompile_ix.clone();
        d[idx_pos..idx_pos + 2].copy_from_slice(&0u16.to_le_bytes());
        assert_ne!(
            u16::from_le_bytes([d[idx_pos], d[idx_pos + 1]]),
            SAME_INSTRUCTION
        );
        assert_eq!(
            extract_single_signature(&d),
            Err(ConsentError::CrossInstructionReference)
        );
    }
}

#[test]
fn check_consent_accepts_valid_and_rejects_tampering() {
    let v = vector();
    assert_eq!(
        check_consent(&v.fields, &v.pubkey, &v.digest, 1_700_000_000),
        Ok(())
    );

    let mut other = v.fields;
    other.nonce += 1;
    assert_eq!(
        check_consent(&other, &v.pubkey, &v.digest, 1_700_000_000),
        Err(ConsentError::MessageDigestMismatch)
    );

    let mut wrong_key = v.pubkey;
    wrong_key[32] ^= 1;
    assert_eq!(
        check_consent(&v.fields, &wrong_key, &v.digest, 1_700_000_000),
        Err(ConsentError::ContributorKeyMismatch)
    );

    assert_eq!(
        check_consent(&v.fields, &v.pubkey, &v.digest, v.fields.expiry + 1),
        Err(ConsentError::ConsentExpired)
    );
}

#[test]
fn record_roundtrip() {
    let v = vector();
    let rec = ConsentRecord {
        bump: 254,
        release_id: v.fields.release_id,
        split_version_hash: v.fields.split_version_hash,
        contributor_id: v.fields.contributor_id,
        passkey_pubkey: v.pubkey,
        digest: v.digest,
        nonce: v.fields.nonce,
        expiry: v.fields.expiry,
        recorded_slot: 123,
        recorded_unix_timestamp: 1_700_000_000,
        payer: [9u8; 32],
    };
    let mut buf = vec![0u8; CONSENT_RECORD_LEN];
    rec.pack_into(&mut buf).unwrap();
    assert_eq!(ConsentRecord::unpack(&buf).unwrap(), rec);
    assert!(rec.pack_into(&mut [0u8; 10]).is_none());
    buf[0] = 0;
    assert!(ConsentRecord::unpack(&buf).is_none());
}
